### Products Index
GET http://localhost:3000/products.json

### Products Show
GET http://localhost:3000/products/3.json

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Take the Day Off Cleansing Balm Makeup Remover",
  "price": 40,
  "image_url":"https://media.ulta.com/i/ulta/2532674?w=720&fmt=webp",
  "description": "a silky lightweight makeup remover that quickly dissolves tenacious eye and face makeups, sunscreens."
}

### Products Update
PATCH http://localhost:3000/products/1.json 
Content-Type: application/json

{
  "price": 160
}

### Product Delete
DELETE http://localhost:3000/products/14.json 

### Supplier Create
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "Dyson",
  "email": "dyson@test",
  "phone_number": "3452945673"
}

### Suppliers Index
GET http://localhost:3000/suppliers

### Supplier Update
PATCH http://localhost:3000/suppliers/3.json 
Content-Type: application/json

{
  "email": "clinique@test"
}

### Supplier Delete
DELETE http://localhost:3000/suppliers/1.json 