### Products Index
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2Nzg4Mzc4NTB9.woPbnyDigCQvpJbsVXuGP8KLLIOXmTZj1qkiPvc_uec

### Products Show
GET http://localhost:3000/products/1.json

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "producttest",
  "price": 1,
  "description": "I am testing my product",
  "inventory": 10,
  "supplier_id": 2,
  "url": "testing.com"
}


### Products Update
PATCH http://localhost:3000/products/1.json 
Content-Type: application/json

{
  "price": 160
}

### Product Delete
DELETE http://localhost:3000/products/9.json 

### Supplier Create
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "test",
  "email": "test@test",
  "phone_number": "3452945673"
}

### Suppliers Index
GET http://localhost:3000/suppliers

### Supplier Update
PATCH http://localhost:3000/suppliers/3.json 
Content-Type: application/json

{
  "email": "clinique@test.com"
}

### Supplier Delete
DELETE http://localhost:3000/suppliers/9.json 

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Lexi",
  "email": "lexi@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Session Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "lexi@test.com",
  "password": "password"
}

### Orders Create
POST http://localhost:3000/orders.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2Nzg5MjcwODN9.JmGQCEyB8GoKwuOe0YwOzohaN8II7Wg6mYsOYpout2g

{
  "product_id": 1,
  "quantity": 2
}

### Orders Show
GET  http://localhost:3000/orders/7.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2Nzg5MjU0MjR9.p7NVlO49vmeLqUglX9UZaiFagtWfZLQ4Uca7Wpd_P48

### Display all Orders
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2NzkwMDk3MjN9.T2wZZnBf6-7eBojoo0rvYDSLNo6EaDCo_RowpcJOtFE