json.id product.id
json.name product.name
json.price product.price
json.description product.description
json.created_at product.created_at
json.updated_at product.updated_at
json.inventory product.inventory
json.supplier product.supplier
json.images product.images
